<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit144c591503601d470872f21e62b6f663
{
    public static $prefixLengthsPsr4 = array (
        'c' => 
        array (
            'chriskacerguis\\RestServer\\' => 26,
        ),
        'F' => 
        array (
            'Firebase\\JWT\\' => 13,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'chriskacerguis\\RestServer\\' => 
        array (
            0 => __DIR__ . '/..' . '/chriskacerguis/codeigniter-restserver/src',
        ),
        'Firebase\\JWT\\' => 
        array (
            0 => __DIR__ . '/..' . '/firebase/php-jwt/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit144c591503601d470872f21e62b6f663::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit144c591503601d470872f21e62b6f663::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
